SET DATABASE UNIQUE NAME HSQLDB332E5E3ECD
SET DATABASE GC 0
SET DATABASE DEFAULT RESULT MEMORY ROWS 0
SET DATABASE EVENT LOG LEVEL 0
SET DATABASE SQL NAMES FALSE
SET DATABASE SQL REFERENCES FALSE
SET DATABASE SQL SIZE TRUE
SET DATABASE SQL TYPES FALSE
SET DATABASE SQL TDC DELETE TRUE
SET DATABASE SQL TDC UPDATE TRUE
SET DATABASE SQL TRANSLATE TTI TYPES TRUE
SET DATABASE SQL CONCAT NULLS TRUE
SET DATABASE SQL UNIQUE NULLS TRUE
SET DATABASE SQL CONVERT TRUNCATE TRUE
SET DATABASE SQL DOUBLE NAN TRUE
SET DATABASE SQL LONGVAR IS LOB FALSE
SET DATABASE TRANSACTION CONTROL LOCKS
SET DATABASE DEFAULT ISOLATION LEVEL READ COMMITTED
SET DATABASE TRANSACTION ROLLBACK ON DEADLOCK TRUE
SET DATABASE TEXT TABLE DEFAULTS ''
SET FILES WRITE DELAY 500 MILLIS
SET FILES BACKUP INCREMENT TRUE
SET FILES CACHE SIZE 10000
SET FILES CACHE ROWS 50000
SET FILES SCALE 8
SET FILES LOB SCALE 32
SET FILES DEFRAG 0
SET FILES NIO TRUE
SET FILES NIO SIZE 256
SET FILES LOG TRUE
SET FILES LOG SIZE 50
CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'
ALTER USER SA SET LOCAL TRUE
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
SET SCHEMA PUBLIC
CREATE MEMORY TABLE PUBLIC.REFERERS(REF_URL VARCHAR(2048))
CREATE MEMORY TABLE PUBLIC.URL_LIST(URL_STRING VARCHAR(2048))
CREATE MEMORY TABLE PUBLIC.UNIQUE_URLS(URL_STRING VARCHAR(2048))
CREATE MEMORY TABLE PUBLIC.URLS_FILES(URL_STRING VARCHAR(2048),FILE_NAME VARCHAR(64))
CREATE MEMORY TABLE PUBLIC.URLS_FILES_TYPES(URL_STRING VARCHAR(2048),FILE_NAME VARCHAR(64),CONTENT_TYPE VARCHAR(256))
CREATE MEMORY TABLE PUBLIC.GOOD_CONTENT_TYPES(URL_STRING VARCHAR(2048),FILE_NAME VARCHAR(64),CONTENT_TYPE VARCHAR(256))
CREATE MEMORY TABLE PUBLIC.BAD_IMAGES(FILE_NAME VARCHAR(64))
CREATE MEMORY TABLE PUBLIC.AD_URLS(URL_STRING VARCHAR(2048),FILE_NAME VARCHAR(64),CONTENT_TYPE VARCHAR(256))
CREATE MEMORY TABLE PUBLIC.LANDING_PAGE_URLS(AD_URL VARCHAR(2048),FILE_NAME VARCHAR(64),CONTENT_TYPE VARCHAR(256),LANDING_PAGE_URL VARCHAR(2048))
ALTER SEQUENCE SYSTEM_LOBS.LOB_ID RESTART WITH 1
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.YES_OR_NO TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.TIME_STAMP TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CARDINAL_NUMBER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CHARACTER_DATA TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.SQL_IDENTIFIER TO PUBLIC
GRANT DBA TO SA
SET SCHEMA SYSTEM_LOBS
INSERT INTO BLOCKS VALUES(0,2147483647,0)
SET SCHEMA PUBLIC
INSERT INTO URL_LIST VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg')
INSERT INTO URL_LIST VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg')
INSERT INTO URL_LIST VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg')
INSERT INTO URL_LIST VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg')
INSERT INTO URL_LIST VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg')
INSERT INTO URL_LIST VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg')
INSERT INTO URL_LIST VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg')
INSERT INTO URL_LIST VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif')
INSERT INTO URL_LIST VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif')
INSERT INTO URL_LIST VALUES('http://us.img.e-planning.net/esb/4/21/1773/37df1150cc1479b5.gif')
INSERT INTO URL_LIST VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf')
INSERT INTO URL_LIST VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg')
INSERT INTO URL_LIST VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif')
INSERT INTO URL_LIST VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif')
INSERT INTO URL_LIST VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf')
INSERT INTO URL_LIST VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf')
INSERT INTO URL_LIST VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0')
INSERT INTO URL_LIST VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0')
INSERT INTO UNIQUE_URLS VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0')
INSERT INTO UNIQUE_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif')
INSERT INTO UNIQUE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif')
INSERT INTO UNIQUE_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf')
INSERT INTO UNIQUE_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf')
INSERT INTO UNIQUE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif')
INSERT INTO UNIQUE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif')
INSERT INTO UNIQUE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg')
INSERT INTO UNIQUE_URLS VALUES('http://us.img.e-planning.net/esb/4/21/1773/37df1150cc1479b5.gif')
INSERT INTO UNIQUE_URLS VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf')
INSERT INTO UNIQUE_URLS VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg')
INSERT INTO URLS_FILES VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0','e5db37d63fd19a76b6eab04de9c4aad35856e4f3')
INSERT INTO URLS_FILES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg','60b27f004e454aca81b0480209cce5081ec52390')
INSERT INTO URLS_FILES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg','cb99b709a1978bd205ab9dfd4c5aaa1fc91c7523')
INSERT INTO URLS_FILES VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg','d5b0a58bc47161b1b8a831084b366f757c4f0b11')
INSERT INTO URLS_FILES VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg','1b641bf4f6b84efcd42920ff1a88ff2f97fb9d08')
INSERT INTO URLS_FILES VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg','c1750bee9c1f7b5dd6f025b645ab6eba5df94175')
INSERT INTO URLS_FILES VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg','0a856eb66ff730bd2edc068b17c0cb51fc09fc4b')
INSERT INTO URLS_FILES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif','d8cea2d0a17ce156a082567ddec8016ba1a8643c')
INSERT INTO URLS_FILES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif','97bfb660c85037edae8468c6e5ce2799364ad26e')
INSERT INTO URLS_FILES VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf','3c18d97d83a768f061fbefea5f5b86cf8adde3eb')
INSERT INTO URLS_FILES VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf','1c1d732e8620c8b8398b8a2bbb18fa67a09b18c2')
INSERT INTO URLS_FILES VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0')
INSERT INTO URLS_FILES VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif','8696eb5c6ace1e47e6f20408b8bc4f3cd01a90d0')
INSERT INTO URLS_FILES VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg','02b2cebadbec73e83a635cdc24a743ad58344e57')
INSERT INTO URLS_FILES VALUES('http://us.img.e-planning.net/esb/4/21/1773/37df1150cc1479b5.gif','c160595c2510600347b6e0dbc61dc55a0d582db1')
INSERT INTO URLS_FILES VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf','2361cc2545a9e1965abbede3f19ac23a5c09ce49')
INSERT INTO URLS_FILES VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg','fdcca642f941caa5995c216b62dd137d40795cb0')
INSERT INTO URLS_FILES_TYPES VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0','e5db37d63fd19a76b6eab04de9c4aad35856e4f3','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg','60b27f004e454aca81b0480209cce5081ec52390','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg','cb99b709a1978bd205ab9dfd4c5aaa1fc91c7523','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg','d5b0a58bc47161b1b8a831084b366f757c4f0b11','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg','1b641bf4f6b84efcd42920ff1a88ff2f97fb9d08','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg','c1750bee9c1f7b5dd6f025b645ab6eba5df94175','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg','0a856eb66ff730bd2edc068b17c0cb51fc09fc4b','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif','d8cea2d0a17ce156a082567ddec8016ba1a8643c','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif','97bfb660c85037edae8468c6e5ce2799364ad26e','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf','3c18d97d83a768f061fbefea5f5b86cf8adde3eb','application/x-shockwave-flash')
INSERT INTO URLS_FILES_TYPES VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf','1c1d732e8620c8b8398b8a2bbb18fa67a09b18c2','application/x-shockwave-flash')
INSERT INTO URLS_FILES_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif','8696eb5c6ace1e47e6f20408b8bc4f3cd01a90d0','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg','02b2cebadbec73e83a635cdc24a743ad58344e57','image/jpeg')
INSERT INTO URLS_FILES_TYPES VALUES('http://us.img.e-planning.net/esb/4/21/1773/37df1150cc1479b5.gif','c160595c2510600347b6e0dbc61dc55a0d582db1','image/gif')
INSERT INTO URLS_FILES_TYPES VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf','2361cc2545a9e1965abbede3f19ac23a5c09ce49','application/x-shockwave-flash')
INSERT INTO URLS_FILES_TYPES VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg','fdcca642f941caa5995c216b62dd137d40795cb0','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://adx.adnxs.com/mapuid?member=181&user=E0','e5db37d63fd19a76b6eab04de9c4aad35856e4f3','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg','60b27f004e454aca81b0480209cce5081ec52390','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg','cb99b709a1978bd205ab9dfd4c5aaa1fc91c7523','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg','d5b0a58bc47161b1b8a831084b366f757c4f0b11','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg','1b641bf4f6b84efcd42920ff1a88ff2f97fb9d08','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg','c1750bee9c1f7b5dd6f025b645ab6eba5df94175','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg','0a856eb66ff730bd2edc068b17c0cb51fc09fc4b','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif','d8cea2d0a17ce156a082567ddec8016ba1a8643c','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif','97bfb660c85037edae8468c6e5ce2799364ad26e','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf','3c18d97d83a768f061fbefea5f5b86cf8adde3eb','application/x-shockwave-flash')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf','1c1d732e8620c8b8398b8a2bbb18fa67a09b18c2','application/x-shockwave-flash')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif','8696eb5c6ace1e47e6f20408b8bc4f3cd01a90d0','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg','02b2cebadbec73e83a635cdc24a743ad58344e57','image/jpeg')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://us.img.e-planning.net/esb/4/21/1773/37df1150cc1479b5.gif','c160595c2510600347b6e0dbc61dc55a0d582db1','image/gif')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf','2361cc2545a9e1965abbede3f19ac23a5c09ce49','application/x-shockwave-flash')
INSERT INTO GOOD_CONTENT_TYPES VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg','fdcca642f941caa5995c216b62dd137d40795cb0','image/jpeg')
INSERT INTO BAD_IMAGES VALUES('c160595c2510600347b6e0dbc61dc55a0d582db1')
INSERT INTO BAD_IMAGES VALUES('e5db37d63fd19a76b6eab04de9c4aad35856e4f3')
INSERT INTO AD_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg','60b27f004e454aca81b0480209cce5081ec52390','image/jpeg')
INSERT INTO AD_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/youtube.jpg','cb99b709a1978bd205ab9dfd4c5aaa1fc91c7523','image/jpeg')
INSERT INTO AD_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg','d5b0a58bc47161b1b8a831084b366f757c4f0b11','image/jpeg')
INSERT INTO AD_URLS VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg','1b641bf4f6b84efcd42920ff1a88ff2f97fb9d08','image/jpeg')
INSERT INTO AD_URLS VALUES('http://altonivel.com.mx/assets/images/banners/btn_empresarias.jpg','c1750bee9c1f7b5dd6f025b645ab6eba5df94175','image/jpeg')
INSERT INTO AD_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg','0a856eb66ff730bd2edc068b17c0cb51fc09fc4b','image/jpeg')
INSERT INTO AD_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif','d8cea2d0a17ce156a082567ddec8016ba1a8643c','image/gif')
INSERT INTO AD_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif','97bfb660c85037edae8468c6e5ce2799364ad26e','image/gif')
INSERT INTO AD_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf','3c18d97d83a768f061fbefea5f5b86cf8adde3eb','application/x-shockwave-flash')
INSERT INTO AD_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf','1c1d732e8620c8b8398b8a2bbb18fa67a09b18c2','application/x-shockwave-flash')
INSERT INTO AD_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0','image/gif')
INSERT INTO AD_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif','8696eb5c6ace1e47e6f20408b8bc4f3cd01a90d0','image/gif')
INSERT INTO AD_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg','02b2cebadbec73e83a635cdc24a743ad58344e57','image/jpeg')
INSERT INTO AD_URLS VALUES('http://us.img.e-planning.net/esb/4/22/1773/0e53f25948c4f399.swf','2361cc2545a9e1965abbede3f19ac23a5c09ce49','application/x-shockwave-flash')
INSERT INTO AD_URLS VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg','fdcca642f941caa5995c216b62dd137d40795cb0','image/jpeg')
INSERT INTO LANDING_PAGE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0','image/gif','http://www.dibujando.org.mx/index.php')
INSERT INTO LANDING_PAGE_URLS VALUES('http://altonivel.com.mx/assets/images/banners/btn_alimentacion.jpg','1b641bf4f6b84efcd42920ff1a88ff2f97fb9d08','image/jpeg','http://www.altonivel.com.mx/12785-alimentacion-saludable-para-un-mejor-desempeno.html')
INSERT INTO LANDING_PAGE_URLS VALUES('http://www.altonivel.com.mx/assets/images/banners/btn_empresas_mexicanas.jpg','fdcca642f941caa5995c216b62dd137d40795cb0','image/jpeg','http://www.altonivel.com.mx/12661-empresas-orgullosamente-mexicanas.html')
INSERT INTO LANDING_PAGE_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/E-Marketing/061211_pop_ups.jpg','60b27f004e454aca81b0480209cce5081ec52390','image/jpeg','http://altonivel.com.mx/17510-pop-ups-buena-estrategia-o-irritante-publicidad.html')
INSERT INTO LANDING_PAGE_URLS VALUES('http://altonivel.com.mx/assets/images/Marketing/Publicidad/101210_humor.jpg','d5b0a58bc47161b1b8a831084b366f757c4f0b11','image/jpeg','http://altonivel.com.mx/17490-como-usar-el-humor-en-una-campana.html')
INSERT INTO LANDING_PAGE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/94fa34616a960f86.gif','8696eb5c6ace1e47e6f20408b8bc4f3cd01a90d0','image/gif','http://www.soyentrepreneur.com/')
INSERT INTO LANDING_PAGE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/d863764efe42acbb.jpg','02b2cebadbec73e83a635cdc24a743ad58344e57','image/jpeg','http://www.altonivel.com.mx/descarga-e-books.html')
INSERT INTO LANDING_PAGE_URLS VALUES('http://us.img.e-planning.net/esb/4/0/1773/8958bda6fba60990.gif','7acf6b8a5c466eb77076ff396a073d0a350874d0','image/gif','http://www.dibujando.org.mx/index.php')
INSERT INTO LANDING_PAGE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/c7e326cd-cecd-46e8-95b1-9d137a541087.gif','97bfb660c85037edae8468c6e5ce2799364ad26e','image/gif','http://www.cadillac.com.mx/content_data/LAAM/MX/es/GMMGM/showroom/cadillac/precios/autos-cadillac-2011-precios-cts-srx-escalade.html?cmp=cadillacsrx_escaladep_dic2011_altonivel_superbanner')
INSERT INTO LANDING_PAGE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-18568/Type-0/10ec7a48-ebb1-48bf-adc3-0f08cde9b61a.gif','d8cea2d0a17ce156a082567ddec8016ba1a8643c','image/gif','http://www.cadillac.com.mx/content_data/LAAM/MX/es/GMMGM/showroom/cadillac/precios/autos-cadillac-2011-precios-cts-srx-escalade.html?cmp=cadillacsrx_escaladep_dic2011_altonivel_boxbanner')
INSERT INTO LANDING_PAGE_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2617_CA_Plasma_BannerSP_300x250.swf','3c18d97d83a768f061fbefea5f5b86cf8adde3eb','application/x-shockwave-flash','http://www.miallstate.com/lp/renters-ca.aspx')
INSERT INTO LANDING_PAGE_URLS VALUES('http://ds.serving-sys.com/BurstingRes///Site-15227/Type-0/61225baa-5d26-4ca1-982b-d3e720ca0faa.jpg','0a856eb66ff730bd2edc068b17c0cb51fc09fc4b','image/jpeg','http://www.bancomer.com.mx/')
INSERT INTO LANDING_PAGE_URLS VALUES('http://s0.2mdn.net/1917241/AHNL2618_CA_Camera_BannerSP_728x90.swf','1c1d732e8620c8b8398b8a2bbb18fa67a09b18c2','application/x-shockwave-flash','http://www.miallstate.com/lp/renters-ca.aspx')
